[tool.poetry]
name = "eli-nabro"
version = "0.1.0"
description = ""
authors = ["eli.nabro <eli.nabro@kakaocorp.com>"]
readme = "README.md"
packages = [{include = "eli"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
